### ISSUE TITLE
いおくじ実装

### ISSUE THREAD

**Issue by mozamimy** [mozamimy/bts-bot#2]
いおくじの仕様わすれちゃった

**Comment by Muddler** [comment]
いおくじ
って発言すると
【ほげ吉】ほげほげほげほげ
って返してくれる感じだった記憶。

**Comment by mozamimy** [comment]
にゃるほど〜

**Comment by mozamimy** [comment]
とりあえずできた https://github.com/mozamimy/bts-bot/pull/7
